# This workflow will upload a dev Python Package to PyPI using Twine when a main branch commit
# is pushed. For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: pypi-dev

# PyPI push triggers whenever we push a commit to main.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 3.11 breaks grpcio-tools.
    - name: Install dependencies
      run: |
        sudo apt-get install -y libprotobuf-dev
        python -m pip install --upgrade pip
        pip install setuptools wheel twine==5.0.0 grpcio-tools==1.48.2
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py --dev sdist bdist_wheel
        twine upload dist/*
